export const userRolesConfig = {
    ADMIN : "ADMIN",
    SUPERADMIN:'SUPERADMIN',
    MANAGER:'MANAGER',
    REGIONAL_MANAGER:'REGIONALMANAGER',
    MARKETING:'MARKETING',
    BILLING:'Billing',
    PHARMACY:'Pharmacy',
    HR:'HR',
    ONLINEMARKETING:'ONLINEMARKETING',
    LOGISTICS:'LOGISTICS',
    REGIONALHEAD:'REGIONALHEAD',
    MARKETINGEXECUTIVE:'MARKETINGEXECUTIVE'




}